language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: npm
  email: null@affinitygamescollective.org
  api_key:
    secure: kpejC4+b72c6r8LO2dFhPjKZwgYyQFPnlZxie5ozuB/PCHXsYhihyzKMTcXmizj/eomb73IwXUCUerG9zLRwiRlQjFIG/GvWBg1TYGm4+V0Kt72TUfV/RLWUFbUD1e8j5SOfmps0L84qTeLrfmwN8YSEGLkrCQfHRe46+ozeRUFGOGWkqMeOnZou8rn80YlLYt4dgp7aB4WQKtKwMhi6TZcxG60lbscYazcoYR/lhJtC4Yw9LcTuGXJk4W6UvKSIFBvywCt3+chxs2U8K8dVxl2Ypk7kHfxsHX2/vurrCvhzC0shwTMRcuxLeG7JgPSydTCBb6ZdBj7UM1NlAbafapjvWZF6LqhntCV7hbGyZmVul9HHS0Aw/01Wkwj0tmLhuOtJS6uE5+MK49C6RfBvQDPQnBsyHsZMShGcsuJDQEFalROMdTvRBiONzakQYRxenhSd0/bzlrrEmLFnJ4Pjvhw+mQ/M1PXdow41iWjm/UxPlDWusO54Ju8qbzpn+Xmlcg6iL8HoQU7PVn2Av2T3+OZ0PgpC2o0j+UbYTm5V0Np9+h8eWznzaRAW9t7lvd8z4LZL+5m6QoJ53WMRTuxwDK4lWHCLEBP2XPerKeOEl/jme9/wnhqCYdPAI9lQKtHhcQmXEWedtDndrKhpN3mxlXQEn2J2tVU47X6qNOlGBT8=
  on:
    tags: true
    repo: null-null-null/ember-flex-menu
